inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Enabled: true
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 15

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Layout/LineLength:
  Enabled: false